DROP TABLE IF EXISTS members;

CREATE TABLE members
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    mssv VARCHAR(225) NOT NULL UNIQUE,
    name VARCHAR(225) NOT NULL,
    role VARCHAR(225),
    timejoin TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
